#!/usr/bin/env python

name_to_dir = {
            "6": "/home/timo/worsch/zasim/"
        }


import subprocess
import json
import os
import sys

workspacedata = json.loads(subprocess.check_output("i3-msg -t get_workspaces".split(" ")))

focused = [ws for ws in workspacedata if ws["focused"] == True]

wsname = focused[0]["name"]

for name in name_to_dir:
    if name.startswith(wsname):
        print name_to_dir[wsname]
        os.chdir(name_to_dir[wsname])
        break

os.system(" ".join(sys.argv[1:]))
