#!/usr/bin/env python

def rgb888to565(rgb):
    r = rgb >> 16
    g = (rgb >> 8) & 0xff
    b = rgb & 0xff

    r = r >> 3
    g = g >> 2
    b = b >> 3

    return b + (g<<5) + (r<<11)

while True:
    x = raw_input("Enter 24-bit color in hex, or blank to end> ").strip()
    if not x:
        break
    if x.startswith('#'):
        x = x.replace('#', '0x')
    try:
        x = int(x, 16)
    except ValueError:
        print "Bad value %r. Try 0xRRGGBB or #RRGGBB." % x
    else:
        print "#%06x" % rgb888to565(x)
